trigger:
  branches:
    include:
      - master
  tags:
    include:
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  jdkVersion: 13.0.2
  jdkVersionMajor: 13
  jdkDownloadUrl: https://download.java.net/java/GA/jdk13.0.2/d4173c853231432d94f001e99d882ca7/8/GPL/openjdk-13.0.2_windows-x64_bin.zip
  jdkInstallPackage: '$(Agent.TempDirectory)\jdk-$(jdkVersion).zip'

steps:
- task: UsePythonVersion@0
  displayName: Setup Python3
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'
- task: PythonScript@0
  displayName: Download JDK
  inputs:
    scriptSource: 'inline'
    script: |
      from urllib.request import urlretrieve
      urlretrieve("$(jdkDownloadUrl)", r"$(jdkInstallPackage)")
- task: JavaToolInstaller@0
  displayName: Install JDK
  inputs:
    versionSpec: $(jdkVersionMajor)
    jdkArchitectureOption: x64
    jdkSourceOption: LocalDirectory
    jdkFile: $(jdkInstallPackage)
    jdkDestinationDirectory: '$(Agent.TempDirectory)\jdk'
    cleanDestinationDirectory: true
- task: Gradle@2
  displayName: Build and Test
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build test release'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: '$(Agent.TempDirectory)\jdk\jdk-$(jdkVersion)'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false
- task: CopyFiles@2
  displayName: Copy Build Artifacts
  inputs:
    SourceFolder: 'build\release'
    Contents: 'Rikki-*.zip*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Build Artifacts'
    publishLocation: 'Container'
- task: GitHubRelease@1
  displayName: Publish GitHub Release
  inputs:
    gitHubConnection: 'rikki'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    assets: '$(Build.ArtifactStagingDirectory)/Rikki-*.zip*'
    addChangeLog: false